name: Build with Pnet on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upgrade Chocolatey
      run: |
        choco upgrade chocolatey
      shell: powershell

    - name: Install Windows SDK
      run: |
        choco install windows-sdk-10.0 -y
        # Replace 'version-number' with the appropriate Windows SDK version number
      shell: powershell

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Check if Visual Studio lib directory exists
      run: |
        $libDirectory = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\lib\x64"
        if (Test-Path -Path $libDirectory -PathType Container) {
          echo "Visual Studio lib directory exists."
        } else {
          echo "Visual Studio lib directory does not exist. Create it or adjust the path."
          exit 1
        }
      shell: powershell

    - name: Copy Packet.lib to Visual Studio lib directory
      run: |
        $libDirectory = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\lib\x64" # Update with your Visual Studio path
        Copy-Item -Path "${{ github.workspace }}/lib/Packet.lib" -Destination $libDirectory
      shell: powershell

    - name: Build with Cargo
      run: |
        cargo build --target x86_64-pc-windows-msvc
