name: Build with Pnet on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Add Packet.lib to MSVC library path
      run: |
        $libPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\lib\x64" # Update with your Visual Studio path
        [System.Environment]::SetEnvironmentVariable("LIB", "$env:LIB;$libPath", [System.EnvironmentVariableTarget]::Machine)
      shell: powershell

    - name: Build with Cargo
      run: |
        cargo build --target x86_64-pc-windows-msvc
      env:
        PKG_CONFIG_PATH: "path_to_packet_lib_directory" # Update with the path to the directory containing Packet.lib
